[package]
name = "eto-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0.14"
tracing = "0.1.36"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
