[package]
name = "eto"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
glob = "0.3.0"
pathdiff = "0.2.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
sha256 = "1.0.3"
tracing = "0.1.36"
walkdir = "2.3.2"
zip = "0.6.2"
